config/routes.rb
Rails.application.routes.draw do

  #  root 'static_pages#home'
  root 'shorten_urls#new'
  get '/shorten_urls', to:'shorten_urls#new'
  post '/shorten_urls', to:'shorten_urls#create'
#  get 'shorten_urls/new'
#  get 'shorten_urls/show'
  get 'shorten_urls/jump'
  get "shorten_urls/jump/:id" => 'shorten_urls#jump'
  post 'shorten_urls/create'
  get 'shorten_urls/delete'
  get '/shorten_urls', to: 'shorten_urls#new'
  get 'sessions/new'
  get '/help' ,to:'static_pages#help'
  get '/about' ,to:'static_pages#about'
  get '/contact' ,to:'static_pages#contact'
  get '/signup' ,to:'users#new'
  post '/signup' ,to:'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  
  get '/:id' => 'shorten_urls#jump'

  
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  
  before_save {self.original_url = original_url.downcase}
  validates :original_url, presence: true
  VALID_URL_REGEX = /\A(http|https):\/\/[\w]+\.[\w]+/
  validates :original_url, format: {with: VALID_URL_REGEX}
  validates :shortened_url, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  validates :name, presence: true, length:{maximum: 50}
  validates :email, presence: true, length:{maximum: 255}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, format: {with: VALID_EMAIL_REGEX}
  validates :email, uniqueness: {case_sensitive: false}
  has_secure_password

  validates :password, presence: true, length:{minimum: 6}

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
  
end

app/controllers/shorten_urls_controller.rb
# coding: utf-8
class ShortenUrlsController < ApplicationController
  def new
    @url = Url.new
  end

  def show
    
  end
  

  def create
    @url = Url.new(params.require(:url).permit(:original_url))

    while
      @url.shortened_url = generate_shortened_url
      if 
        !Url.exists?(:shortened_url => @url.shortened_url)        
        break
      end
    end
    if @url.save
      flash[:info] = "短縮後のURLは#{@url.shortened_url}です！"
      redirect_to shorten_urls_path
    elsif
      render 'new'
    end  
  end

  def delete
  end


  def jump
    @url = Url.find_by_shortened_url(generate_shortened_url_from_id(params[:id]))
    if @url
      redirect_to(@url.original_url)
    else
      redirect_to :action=>'new'
    end
  end
  private
  def generate_shortened_url_from_id(id)
    "http://" + request.host_with_port + '/' + id
  end
  def generate_shortened_url
    generate_shortened_url_from_id(('a'..'z').to_a.shuffle[0..7].join)
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
    
  end
end

app/controllers/users_controller.rb
# coding: utf-8
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end
  

app/helpers/application_helper.rb
# coding: utf-8
module ApplicationHelper
  #ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " |" + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user =nil
  end
end

app/helpers/shorten_urls_helper.rb
module ShortenUrlsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Shorten-URLs
        by s8_ken
    </small>
    <nav>
        <ul>
            <li><%= link_to "About",   about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><a href="https://www.yahoo.co.jp/">News</a></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "Shorten-URLs", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Help", help_path %></li>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application',
'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= full_title(yield(:title)) %></title>
        <%= render 'layouts/rails_default' %>
        <%= render 'layouts/shim' %>
    </head>
    <body>
        <%= render 'layouts/header' %>
        <div class="container">
            <% flash.each do |message_type, message| %>
                 <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
            <% end %>
            <%= yield %>
            <%= render 'layouts/footer'%>
            <%= debug(params) if Rails.env.development? %>
        </div>
    </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shorten_urls/create.html.erb
<h1>ShortenUrls#create</h1>
<p>Find me in app/views/shorten_urls/create.html.erb</p>

app/views/shorten_urls/delete.html.erb
<h1>ShortenUrls#delete</h1>
<p>Find me in app/views/shorten_urls/delete.html.erb</p>

app/views/shorten_urls/new.html.erb
<% provide(:title, 'Shorten-URLs') %>
<h1>Shorten-URLs</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
		<%= form_for @url , url:shorten_urls_path do |f| %>
			<% if @url.errors.any? %>
				<div id="error_explanation">
					<h2><%= @url.errors.count %>件のエラーがあります。</h2>
					
					<ul>
						<% @url.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			<% end %>
			<%= f.label :original_url %>
			<%= f.text_field :original_url,class: 'form-control' %>
			<%= f.submit "Create Shortened URL", class: "btn btn-primary" %>
		<% end %>
    </div>
</div>

app/views/shorten_urls/show.html.erb
<h1>ShortenUrls#show</h1>
<p>Find me in app/views/shorten_urls/show.html.erb</p>

app/views/static_pages/about.html.erb
<% provide(:title, "about") %>
<h1>Shorten-URLs</h1>
<p>
	<a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
</p>
<p>上記のチュートリアルを参考に作成</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "help") %>
<h1>Shorten-URLs</h1>
<p>
	s8_kenが提供するURLの短縮化サービスです。
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>
    Welcome to the Sample App
  </h1>

  <h2>
    This is the home page for the
    <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  <p>Or Lets Shorten URL right now!!</p>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
    'http://rubyonrails.org/' %>

<%#= image_tag("kitten.jpg") %>

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user, url: signup_path) do |f| %>
            <%= render 'shared/error_messages' %>

            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>

            <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user %>
                <%= @user.name %>
            </h1>
        </section>
    </aside>
</div>